//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApmObservation) DeepCopyInto(out *ApmObservation) {
	*out = *in
	if in.HTTPEndpoint != nil {
		in, out := &in.HTTPEndpoint, &out.HTTPEndpoint
		*out = new(string)
		**out = **in
	}
	if in.HTTPSEndpoint != nil {
		in, out := &in.HTTPSEndpoint, &out.HTTPSEndpoint
		*out = new(string)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.ResourceID != nil {
		in, out := &in.ResourceID, &out.ResourceID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApmObservation.
func (in *ApmObservation) DeepCopy() *ApmObservation {
	if in == nil {
		return nil
	}
	out := new(ApmObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApmParameters) DeepCopyInto(out *ApmParameters) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make([]ConfigParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ElasticsearchClusterRefID != nil {
		in, out := &in.ElasticsearchClusterRefID, &out.ElasticsearchClusterRefID
		*out = new(string)
		**out = **in
	}
	if in.RefID != nil {
		in, out := &in.RefID, &out.RefID
		*out = new(string)
		**out = **in
	}
	if in.Topology != nil {
		in, out := &in.Topology, &out.Topology
		*out = make([]TopologyParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApmParameters.
func (in *ApmParameters) DeepCopy() *ApmParameters {
	if in == nil {
		return nil
	}
	out := new(ApmParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalingObservation) DeepCopyInto(out *AutoscalingObservation) {
	*out = *in
	if in.PolicyOverrideJSON != nil {
		in, out := &in.PolicyOverrideJSON, &out.PolicyOverrideJSON
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalingObservation.
func (in *AutoscalingObservation) DeepCopy() *AutoscalingObservation {
	if in == nil {
		return nil
	}
	out := new(AutoscalingObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalingParameters) DeepCopyInto(out *AutoscalingParameters) {
	*out = *in
	if in.MaxSize != nil {
		in, out := &in.MaxSize, &out.MaxSize
		*out = new(string)
		**out = **in
	}
	if in.MaxSizeResource != nil {
		in, out := &in.MaxSizeResource, &out.MaxSizeResource
		*out = new(string)
		**out = **in
	}
	if in.MinSize != nil {
		in, out := &in.MinSize, &out.MinSize
		*out = new(string)
		**out = **in
	}
	if in.MinSizeResource != nil {
		in, out := &in.MinSizeResource, &out.MinSizeResource
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalingParameters.
func (in *AutoscalingParameters) DeepCopy() *AutoscalingParameters {
	if in == nil {
		return nil
	}
	out := new(AutoscalingParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigObservation) DeepCopyInto(out *ConfigObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigObservation.
func (in *ConfigObservation) DeepCopy() *ConfigObservation {
	if in == nil {
		return nil
	}
	out := new(ConfigObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigParameters) DeepCopyInto(out *ConfigParameters) {
	*out = *in
	if in.DebugEnabled != nil {
		in, out := &in.DebugEnabled, &out.DebugEnabled
		*out = new(bool)
		**out = **in
	}
	if in.DockerImage != nil {
		in, out := &in.DockerImage, &out.DockerImage
		*out = new(string)
		**out = **in
	}
	if in.UserSettingsJSON != nil {
		in, out := &in.UserSettingsJSON, &out.UserSettingsJSON
		*out = new(string)
		**out = **in
	}
	if in.UserSettingsOverrideJSON != nil {
		in, out := &in.UserSettingsOverrideJSON, &out.UserSettingsOverrideJSON
		*out = new(string)
		**out = **in
	}
	if in.UserSettingsOverrideYaml != nil {
		in, out := &in.UserSettingsOverrideYaml, &out.UserSettingsOverrideYaml
		*out = new(string)
		**out = **in
	}
	if in.UserSettingsYaml != nil {
		in, out := &in.UserSettingsYaml, &out.UserSettingsYaml
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigParameters.
func (in *ConfigParameters) DeepCopy() *ConfigParameters {
	if in == nil {
		return nil
	}
	out := new(ConfigParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Deployment) DeepCopyInto(out *Deployment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Deployment.
func (in *Deployment) DeepCopy() *Deployment {
	if in == nil {
		return nil
	}
	out := new(Deployment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Deployment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentList) DeepCopyInto(out *DeploymentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Deployment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentList.
func (in *DeploymentList) DeepCopy() *DeploymentList {
	if in == nil {
		return nil
	}
	out := new(DeploymentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DeploymentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentObservation) DeepCopyInto(out *DeploymentObservation) {
	*out = *in
	if in.ElasticsearchUsername != nil {
		in, out := &in.ElasticsearchUsername, &out.ElasticsearchUsername
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentObservation.
func (in *DeploymentObservation) DeepCopy() *DeploymentObservation {
	if in == nil {
		return nil
	}
	out := new(DeploymentObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentParameters) DeepCopyInto(out *DeploymentParameters) {
	*out = *in
	if in.Alias != nil {
		in, out := &in.Alias, &out.Alias
		*out = new(string)
		**out = **in
	}
	if in.Apm != nil {
		in, out := &in.Apm, &out.Apm
		*out = make([]ApmParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DeploymentTemplateID != nil {
		in, out := &in.DeploymentTemplateID, &out.DeploymentTemplateID
		*out = new(string)
		**out = **in
	}
	if in.Elasticsearch != nil {
		in, out := &in.Elasticsearch, &out.Elasticsearch
		*out = make([]ElasticsearchParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.EnterpriseSearch != nil {
		in, out := &in.EnterpriseSearch, &out.EnterpriseSearch
		*out = make([]EnterpriseSearchParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Kibana != nil {
		in, out := &in.Kibana, &out.Kibana
		*out = make([]KibanaParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Observability != nil {
		in, out := &in.Observability, &out.Observability
		*out = make([]ObservabilityParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.RequestID != nil {
		in, out := &in.RequestID, &out.RequestID
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.TrafficFilter != nil {
		in, out := &in.TrafficFilter, &out.TrafficFilter
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentParameters.
func (in *DeploymentParameters) DeepCopy() *DeploymentParameters {
	if in == nil {
		return nil
	}
	out := new(DeploymentParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentSpec) DeepCopyInto(out *DeploymentSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentSpec.
func (in *DeploymentSpec) DeepCopy() *DeploymentSpec {
	if in == nil {
		return nil
	}
	out := new(DeploymentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentStatus) DeepCopyInto(out *DeploymentStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentStatus.
func (in *DeploymentStatus) DeepCopy() *DeploymentStatus {
	if in == nil {
		return nil
	}
	out := new(DeploymentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticsearchConfigObservation) DeepCopyInto(out *ElasticsearchConfigObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticsearchConfigObservation.
func (in *ElasticsearchConfigObservation) DeepCopy() *ElasticsearchConfigObservation {
	if in == nil {
		return nil
	}
	out := new(ElasticsearchConfigObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticsearchConfigParameters) DeepCopyInto(out *ElasticsearchConfigParameters) {
	*out = *in
	if in.DockerImage != nil {
		in, out := &in.DockerImage, &out.DockerImage
		*out = new(string)
		**out = **in
	}
	if in.Plugins != nil {
		in, out := &in.Plugins, &out.Plugins
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.UserSettingsJSON != nil {
		in, out := &in.UserSettingsJSON, &out.UserSettingsJSON
		*out = new(string)
		**out = **in
	}
	if in.UserSettingsOverrideJSON != nil {
		in, out := &in.UserSettingsOverrideJSON, &out.UserSettingsOverrideJSON
		*out = new(string)
		**out = **in
	}
	if in.UserSettingsOverrideYaml != nil {
		in, out := &in.UserSettingsOverrideYaml, &out.UserSettingsOverrideYaml
		*out = new(string)
		**out = **in
	}
	if in.UserSettingsYaml != nil {
		in, out := &in.UserSettingsYaml, &out.UserSettingsYaml
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticsearchConfigParameters.
func (in *ElasticsearchConfigParameters) DeepCopy() *ElasticsearchConfigParameters {
	if in == nil {
		return nil
	}
	out := new(ElasticsearchConfigParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticsearchObservation) DeepCopyInto(out *ElasticsearchObservation) {
	*out = *in
	if in.CloudID != nil {
		in, out := &in.CloudID, &out.CloudID
		*out = new(string)
		**out = **in
	}
	if in.HTTPEndpoint != nil {
		in, out := &in.HTTPEndpoint, &out.HTTPEndpoint
		*out = new(string)
		**out = **in
	}
	if in.HTTPSEndpoint != nil {
		in, out := &in.HTTPSEndpoint, &out.HTTPSEndpoint
		*out = new(string)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.ResourceID != nil {
		in, out := &in.ResourceID, &out.ResourceID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticsearchObservation.
func (in *ElasticsearchObservation) DeepCopy() *ElasticsearchObservation {
	if in == nil {
		return nil
	}
	out := new(ElasticsearchObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticsearchParameters) DeepCopyInto(out *ElasticsearchParameters) {
	*out = *in
	if in.Autoscale != nil {
		in, out := &in.Autoscale, &out.Autoscale
		*out = new(string)
		**out = **in
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make([]ElasticsearchConfigParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Extension != nil {
		in, out := &in.Extension, &out.Extension
		*out = make([]ExtensionParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RefID != nil {
		in, out := &in.RefID, &out.RefID
		*out = new(string)
		**out = **in
	}
	if in.RemoteCluster != nil {
		in, out := &in.RemoteCluster, &out.RemoteCluster
		*out = make([]RemoteClusterParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SnapshotSource != nil {
		in, out := &in.SnapshotSource, &out.SnapshotSource
		*out = make([]SnapshotSourceParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Topology != nil {
		in, out := &in.Topology, &out.Topology
		*out = make([]ElasticsearchTopologyParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TrustAccount != nil {
		in, out := &in.TrustAccount, &out.TrustAccount
		*out = make([]TrustAccountParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TrustExternal != nil {
		in, out := &in.TrustExternal, &out.TrustExternal
		*out = make([]TrustExternalParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticsearchParameters.
func (in *ElasticsearchParameters) DeepCopy() *ElasticsearchParameters {
	if in == nil {
		return nil
	}
	out := new(ElasticsearchParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticsearchTopologyObservation) DeepCopyInto(out *ElasticsearchTopologyObservation) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make([]TopologyConfigObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.InstanceConfigurationID != nil {
		in, out := &in.InstanceConfigurationID, &out.InstanceConfigurationID
		*out = new(string)
		**out = **in
	}
	if in.NodeRoles != nil {
		in, out := &in.NodeRoles, &out.NodeRoles
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticsearchTopologyObservation.
func (in *ElasticsearchTopologyObservation) DeepCopy() *ElasticsearchTopologyObservation {
	if in == nil {
		return nil
	}
	out := new(ElasticsearchTopologyObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticsearchTopologyParameters) DeepCopyInto(out *ElasticsearchTopologyParameters) {
	*out = *in
	if in.Autoscaling != nil {
		in, out := &in.Autoscaling, &out.Autoscaling
		*out = make([]AutoscalingParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.NodeTypeData != nil {
		in, out := &in.NodeTypeData, &out.NodeTypeData
		*out = new(string)
		**out = **in
	}
	if in.NodeTypeIngest != nil {
		in, out := &in.NodeTypeIngest, &out.NodeTypeIngest
		*out = new(string)
		**out = **in
	}
	if in.NodeTypeML != nil {
		in, out := &in.NodeTypeML, &out.NodeTypeML
		*out = new(string)
		**out = **in
	}
	if in.NodeTypeMaster != nil {
		in, out := &in.NodeTypeMaster, &out.NodeTypeMaster
		*out = new(string)
		**out = **in
	}
	if in.Size != nil {
		in, out := &in.Size, &out.Size
		*out = new(string)
		**out = **in
	}
	if in.SizeResource != nil {
		in, out := &in.SizeResource, &out.SizeResource
		*out = new(string)
		**out = **in
	}
	if in.ZoneCount != nil {
		in, out := &in.ZoneCount, &out.ZoneCount
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticsearchTopologyParameters.
func (in *ElasticsearchTopologyParameters) DeepCopy() *ElasticsearchTopologyParameters {
	if in == nil {
		return nil
	}
	out := new(ElasticsearchTopologyParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnterpriseSearchConfigObservation) DeepCopyInto(out *EnterpriseSearchConfigObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnterpriseSearchConfigObservation.
func (in *EnterpriseSearchConfigObservation) DeepCopy() *EnterpriseSearchConfigObservation {
	if in == nil {
		return nil
	}
	out := new(EnterpriseSearchConfigObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnterpriseSearchConfigParameters) DeepCopyInto(out *EnterpriseSearchConfigParameters) {
	*out = *in
	if in.DockerImage != nil {
		in, out := &in.DockerImage, &out.DockerImage
		*out = new(string)
		**out = **in
	}
	if in.UserSettingsJSON != nil {
		in, out := &in.UserSettingsJSON, &out.UserSettingsJSON
		*out = new(string)
		**out = **in
	}
	if in.UserSettingsOverrideJSON != nil {
		in, out := &in.UserSettingsOverrideJSON, &out.UserSettingsOverrideJSON
		*out = new(string)
		**out = **in
	}
	if in.UserSettingsOverrideYaml != nil {
		in, out := &in.UserSettingsOverrideYaml, &out.UserSettingsOverrideYaml
		*out = new(string)
		**out = **in
	}
	if in.UserSettingsYaml != nil {
		in, out := &in.UserSettingsYaml, &out.UserSettingsYaml
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnterpriseSearchConfigParameters.
func (in *EnterpriseSearchConfigParameters) DeepCopy() *EnterpriseSearchConfigParameters {
	if in == nil {
		return nil
	}
	out := new(EnterpriseSearchConfigParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnterpriseSearchObservation) DeepCopyInto(out *EnterpriseSearchObservation) {
	*out = *in
	if in.HTTPEndpoint != nil {
		in, out := &in.HTTPEndpoint, &out.HTTPEndpoint
		*out = new(string)
		**out = **in
	}
	if in.HTTPSEndpoint != nil {
		in, out := &in.HTTPSEndpoint, &out.HTTPSEndpoint
		*out = new(string)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.ResourceID != nil {
		in, out := &in.ResourceID, &out.ResourceID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnterpriseSearchObservation.
func (in *EnterpriseSearchObservation) DeepCopy() *EnterpriseSearchObservation {
	if in == nil {
		return nil
	}
	out := new(EnterpriseSearchObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnterpriseSearchParameters) DeepCopyInto(out *EnterpriseSearchParameters) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make([]EnterpriseSearchConfigParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ElasticsearchClusterRefID != nil {
		in, out := &in.ElasticsearchClusterRefID, &out.ElasticsearchClusterRefID
		*out = new(string)
		**out = **in
	}
	if in.RefID != nil {
		in, out := &in.RefID, &out.RefID
		*out = new(string)
		**out = **in
	}
	if in.Topology != nil {
		in, out := &in.Topology, &out.Topology
		*out = make([]EnterpriseSearchTopologyParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnterpriseSearchParameters.
func (in *EnterpriseSearchParameters) DeepCopy() *EnterpriseSearchParameters {
	if in == nil {
		return nil
	}
	out := new(EnterpriseSearchParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnterpriseSearchTopologyObservation) DeepCopyInto(out *EnterpriseSearchTopologyObservation) {
	*out = *in
	if in.NodeTypeAppserver != nil {
		in, out := &in.NodeTypeAppserver, &out.NodeTypeAppserver
		*out = new(bool)
		**out = **in
	}
	if in.NodeTypeConnector != nil {
		in, out := &in.NodeTypeConnector, &out.NodeTypeConnector
		*out = new(bool)
		**out = **in
	}
	if in.NodeTypeWorker != nil {
		in, out := &in.NodeTypeWorker, &out.NodeTypeWorker
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnterpriseSearchTopologyObservation.
func (in *EnterpriseSearchTopologyObservation) DeepCopy() *EnterpriseSearchTopologyObservation {
	if in == nil {
		return nil
	}
	out := new(EnterpriseSearchTopologyObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnterpriseSearchTopologyParameters) DeepCopyInto(out *EnterpriseSearchTopologyParameters) {
	*out = *in
	if in.InstanceConfigurationID != nil {
		in, out := &in.InstanceConfigurationID, &out.InstanceConfigurationID
		*out = new(string)
		**out = **in
	}
	if in.Size != nil {
		in, out := &in.Size, &out.Size
		*out = new(string)
		**out = **in
	}
	if in.SizeResource != nil {
		in, out := &in.SizeResource, &out.SizeResource
		*out = new(string)
		**out = **in
	}
	if in.ZoneCount != nil {
		in, out := &in.ZoneCount, &out.ZoneCount
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnterpriseSearchTopologyParameters.
func (in *EnterpriseSearchTopologyParameters) DeepCopy() *EnterpriseSearchTopologyParameters {
	if in == nil {
		return nil
	}
	out := new(EnterpriseSearchTopologyParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtensionObservation) DeepCopyInto(out *ExtensionObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtensionObservation.
func (in *ExtensionObservation) DeepCopy() *ExtensionObservation {
	if in == nil {
		return nil
	}
	out := new(ExtensionObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtensionParameters) DeepCopyInto(out *ExtensionParameters) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.URL != nil {
		in, out := &in.URL, &out.URL
		*out = new(string)
		**out = **in
	}
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtensionParameters.
func (in *ExtensionParameters) DeepCopy() *ExtensionParameters {
	if in == nil {
		return nil
	}
	out := new(ExtensionParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KibanaConfigObservation) DeepCopyInto(out *KibanaConfigObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KibanaConfigObservation.
func (in *KibanaConfigObservation) DeepCopy() *KibanaConfigObservation {
	if in == nil {
		return nil
	}
	out := new(KibanaConfigObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KibanaConfigParameters) DeepCopyInto(out *KibanaConfigParameters) {
	*out = *in
	if in.DockerImage != nil {
		in, out := &in.DockerImage, &out.DockerImage
		*out = new(string)
		**out = **in
	}
	if in.UserSettingsJSON != nil {
		in, out := &in.UserSettingsJSON, &out.UserSettingsJSON
		*out = new(string)
		**out = **in
	}
	if in.UserSettingsOverrideJSON != nil {
		in, out := &in.UserSettingsOverrideJSON, &out.UserSettingsOverrideJSON
		*out = new(string)
		**out = **in
	}
	if in.UserSettingsOverrideYaml != nil {
		in, out := &in.UserSettingsOverrideYaml, &out.UserSettingsOverrideYaml
		*out = new(string)
		**out = **in
	}
	if in.UserSettingsYaml != nil {
		in, out := &in.UserSettingsYaml, &out.UserSettingsYaml
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KibanaConfigParameters.
func (in *KibanaConfigParameters) DeepCopy() *KibanaConfigParameters {
	if in == nil {
		return nil
	}
	out := new(KibanaConfigParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KibanaObservation) DeepCopyInto(out *KibanaObservation) {
	*out = *in
	if in.HTTPEndpoint != nil {
		in, out := &in.HTTPEndpoint, &out.HTTPEndpoint
		*out = new(string)
		**out = **in
	}
	if in.HTTPSEndpoint != nil {
		in, out := &in.HTTPSEndpoint, &out.HTTPSEndpoint
		*out = new(string)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.ResourceID != nil {
		in, out := &in.ResourceID, &out.ResourceID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KibanaObservation.
func (in *KibanaObservation) DeepCopy() *KibanaObservation {
	if in == nil {
		return nil
	}
	out := new(KibanaObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KibanaParameters) DeepCopyInto(out *KibanaParameters) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make([]KibanaConfigParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ElasticsearchClusterRefID != nil {
		in, out := &in.ElasticsearchClusterRefID, &out.ElasticsearchClusterRefID
		*out = new(string)
		**out = **in
	}
	if in.RefID != nil {
		in, out := &in.RefID, &out.RefID
		*out = new(string)
		**out = **in
	}
	if in.Topology != nil {
		in, out := &in.Topology, &out.Topology
		*out = make([]KibanaTopologyParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KibanaParameters.
func (in *KibanaParameters) DeepCopy() *KibanaParameters {
	if in == nil {
		return nil
	}
	out := new(KibanaParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KibanaTopologyObservation) DeepCopyInto(out *KibanaTopologyObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KibanaTopologyObservation.
func (in *KibanaTopologyObservation) DeepCopy() *KibanaTopologyObservation {
	if in == nil {
		return nil
	}
	out := new(KibanaTopologyObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KibanaTopologyParameters) DeepCopyInto(out *KibanaTopologyParameters) {
	*out = *in
	if in.InstanceConfigurationID != nil {
		in, out := &in.InstanceConfigurationID, &out.InstanceConfigurationID
		*out = new(string)
		**out = **in
	}
	if in.Size != nil {
		in, out := &in.Size, &out.Size
		*out = new(string)
		**out = **in
	}
	if in.SizeResource != nil {
		in, out := &in.SizeResource, &out.SizeResource
		*out = new(string)
		**out = **in
	}
	if in.ZoneCount != nil {
		in, out := &in.ZoneCount, &out.ZoneCount
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KibanaTopologyParameters.
func (in *KibanaTopologyParameters) DeepCopy() *KibanaTopologyParameters {
	if in == nil {
		return nil
	}
	out := new(KibanaTopologyParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObservabilityObservation) DeepCopyInto(out *ObservabilityObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObservabilityObservation.
func (in *ObservabilityObservation) DeepCopy() *ObservabilityObservation {
	if in == nil {
		return nil
	}
	out := new(ObservabilityObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObservabilityParameters) DeepCopyInto(out *ObservabilityParameters) {
	*out = *in
	if in.DeploymentID != nil {
		in, out := &in.DeploymentID, &out.DeploymentID
		*out = new(string)
		**out = **in
	}
	if in.Logs != nil {
		in, out := &in.Logs, &out.Logs
		*out = new(bool)
		**out = **in
	}
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = new(bool)
		**out = **in
	}
	if in.RefID != nil {
		in, out := &in.RefID, &out.RefID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObservabilityParameters.
func (in *ObservabilityParameters) DeepCopy() *ObservabilityParameters {
	if in == nil {
		return nil
	}
	out := new(ObservabilityParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoteClusterObservation) DeepCopyInto(out *RemoteClusterObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoteClusterObservation.
func (in *RemoteClusterObservation) DeepCopy() *RemoteClusterObservation {
	if in == nil {
		return nil
	}
	out := new(RemoteClusterObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoteClusterParameters) DeepCopyInto(out *RemoteClusterParameters) {
	*out = *in
	if in.Alias != nil {
		in, out := &in.Alias, &out.Alias
		*out = new(string)
		**out = **in
	}
	if in.DeploymentID != nil {
		in, out := &in.DeploymentID, &out.DeploymentID
		*out = new(string)
		**out = **in
	}
	if in.RefID != nil {
		in, out := &in.RefID, &out.RefID
		*out = new(string)
		**out = **in
	}
	if in.SkipUnavailable != nil {
		in, out := &in.SkipUnavailable, &out.SkipUnavailable
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoteClusterParameters.
func (in *RemoteClusterParameters) DeepCopy() *RemoteClusterParameters {
	if in == nil {
		return nil
	}
	out := new(RemoteClusterParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapshotSourceObservation) DeepCopyInto(out *SnapshotSourceObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapshotSourceObservation.
func (in *SnapshotSourceObservation) DeepCopy() *SnapshotSourceObservation {
	if in == nil {
		return nil
	}
	out := new(SnapshotSourceObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapshotSourceParameters) DeepCopyInto(out *SnapshotSourceParameters) {
	*out = *in
	if in.SnapshotName != nil {
		in, out := &in.SnapshotName, &out.SnapshotName
		*out = new(string)
		**out = **in
	}
	if in.SourceElasticsearchClusterID != nil {
		in, out := &in.SourceElasticsearchClusterID, &out.SourceElasticsearchClusterID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapshotSourceParameters.
func (in *SnapshotSourceParameters) DeepCopy() *SnapshotSourceParameters {
	if in == nil {
		return nil
	}
	out := new(SnapshotSourceParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopologyConfigObservation) DeepCopyInto(out *TopologyConfigObservation) {
	*out = *in
	if in.Plugins != nil {
		in, out := &in.Plugins, &out.Plugins
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.UserSettingsJSON != nil {
		in, out := &in.UserSettingsJSON, &out.UserSettingsJSON
		*out = new(string)
		**out = **in
	}
	if in.UserSettingsOverrideJSON != nil {
		in, out := &in.UserSettingsOverrideJSON, &out.UserSettingsOverrideJSON
		*out = new(string)
		**out = **in
	}
	if in.UserSettingsOverrideYaml != nil {
		in, out := &in.UserSettingsOverrideYaml, &out.UserSettingsOverrideYaml
		*out = new(string)
		**out = **in
	}
	if in.UserSettingsYaml != nil {
		in, out := &in.UserSettingsYaml, &out.UserSettingsYaml
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopologyConfigObservation.
func (in *TopologyConfigObservation) DeepCopy() *TopologyConfigObservation {
	if in == nil {
		return nil
	}
	out := new(TopologyConfigObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopologyConfigParameters) DeepCopyInto(out *TopologyConfigParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopologyConfigParameters.
func (in *TopologyConfigParameters) DeepCopy() *TopologyConfigParameters {
	if in == nil {
		return nil
	}
	out := new(TopologyConfigParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopologyObservation) DeepCopyInto(out *TopologyObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopologyObservation.
func (in *TopologyObservation) DeepCopy() *TopologyObservation {
	if in == nil {
		return nil
	}
	out := new(TopologyObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopologyParameters) DeepCopyInto(out *TopologyParameters) {
	*out = *in
	if in.InstanceConfigurationID != nil {
		in, out := &in.InstanceConfigurationID, &out.InstanceConfigurationID
		*out = new(string)
		**out = **in
	}
	if in.Size != nil {
		in, out := &in.Size, &out.Size
		*out = new(string)
		**out = **in
	}
	if in.SizeResource != nil {
		in, out := &in.SizeResource, &out.SizeResource
		*out = new(string)
		**out = **in
	}
	if in.ZoneCount != nil {
		in, out := &in.ZoneCount, &out.ZoneCount
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopologyParameters.
func (in *TopologyParameters) DeepCopy() *TopologyParameters {
	if in == nil {
		return nil
	}
	out := new(TopologyParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrustAccountObservation) DeepCopyInto(out *TrustAccountObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrustAccountObservation.
func (in *TrustAccountObservation) DeepCopy() *TrustAccountObservation {
	if in == nil {
		return nil
	}
	out := new(TrustAccountObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrustAccountParameters) DeepCopyInto(out *TrustAccountParameters) {
	*out = *in
	if in.AccountID != nil {
		in, out := &in.AccountID, &out.AccountID
		*out = new(string)
		**out = **in
	}
	if in.TrustAll != nil {
		in, out := &in.TrustAll, &out.TrustAll
		*out = new(bool)
		**out = **in
	}
	if in.TrustAllowlist != nil {
		in, out := &in.TrustAllowlist, &out.TrustAllowlist
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrustAccountParameters.
func (in *TrustAccountParameters) DeepCopy() *TrustAccountParameters {
	if in == nil {
		return nil
	}
	out := new(TrustAccountParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrustExternalObservation) DeepCopyInto(out *TrustExternalObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrustExternalObservation.
func (in *TrustExternalObservation) DeepCopy() *TrustExternalObservation {
	if in == nil {
		return nil
	}
	out := new(TrustExternalObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrustExternalParameters) DeepCopyInto(out *TrustExternalParameters) {
	*out = *in
	if in.RelationshipID != nil {
		in, out := &in.RelationshipID, &out.RelationshipID
		*out = new(string)
		**out = **in
	}
	if in.TrustAll != nil {
		in, out := &in.TrustAll, &out.TrustAll
		*out = new(bool)
		**out = **in
	}
	if in.TrustAllowlist != nil {
		in, out := &in.TrustAllowlist, &out.TrustAllowlist
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrustExternalParameters.
func (in *TrustExternalParameters) DeepCopy() *TrustExternalParameters {
	if in == nil {
		return nil
	}
	out := new(TrustExternalParameters)
	in.DeepCopyInto(out)
	return out
}
